repos:
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.4.1
    hooks:
      - id: prettier
        files: \.(cjs|cts|js|jsx|mjs|mts|ts|tsx|json|md|mdx|yaml|yml)$
  - repo: local
    hooks:
      - id: tsc
        name: tsc
        entry: pnpm exec tsc -p tsconfig.json --noEmit
        language: system
        files: \.ts$
        pass_filenames: false
      - id: oxlint
        name: oxlint
        entry: npx --yes oxlint --max-warnings=0 --fix
        language: system
        files: \.(cjs|cts|js|jsx|mjs|mts|ts|tsx)$
        pass_filenames: true
      - id: cargo-fmt
        name: cargo-fmt
        entry: cargo fmt --all
        language: system
        files: \.rs$
        pass_filenames: false
      - id: cargo-clippy
        name: cargo-clippy
        entry: cargo clippy --locked --all-targets --all-features --fix --allow-dirty --allow-staged -- -D warnings
        language: system
        files: \.rs$
        pass_filenames: false
